name: Deploy Docs
on:
    push:
        branches:
            - main
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: pages
    cancel-in-progress: false

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
            - name: Copy Changelog
              run: cp CHANGELOG.md docs/
            - name: Build Docs
              run: cd docs && npm install && npm run build
            - uses: actions/configure-pages@v3
            - uses: actions/upload-pages-artifact@v1
              with:
                  path: docs/.vitepress/dist
            - name: Deploy
              id: deployment
              uses: actions/deploy-pages@v2
